apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-service
  namespace: martinus-nginx-test
spec:
  selector:
    app: nginx-hello
  ports:
    - port: 80
      targetPort: 30711
  type: LoadBalancer
